theme: jekyll-theme-slate
navigation:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv"
  - title: "Publications"
    url: "/publications"
  - title: "Charit√© Pipelines"
    url: "/charite-infectious-diseases-pipelines/"
# This tells Jekyll to include the custom stylesheet
sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      css: "/assets/css/custom.css"
